"use client";

import { useMemo, useState } from "react";
import { analyzeCv } from "@/lib/analysis";

export function AtsChecker() {
  const [text, setText] = useState("");
  const [checked, setChecked] = useState(false);
  const result = useMemo(() => analyzeCv(text), [text]);
  const filename = result.keywords.slice(0, 2).join("-") || "nome-cognome-ruolo";
  return <div className="grid gap-6 lg:grid-cols-[.95fr_1.05fr]"><div className="card p-5 sm:p-7"><label className="label">Testo del CV<textarea className="input min-h-[360px] resize-y" value={text} onChange={(e) => { setText(e.target.value); setChecked(false); }} placeholder="Incolla qui il testo del tuo CV. Includi titoli di sezione, contatti ed esperienze." /></label><button className="btn btn-primary mt-5 w-full sm:w-auto" disabled={!text.trim()} onClick={() => setChecked(true)}>Analizza il CV</button><p className="mt-5 text-xs leading-5 text-[#65736f]">Questo controllo non garantisce un colloquio e non sostituisce la valutazione di un recruiter. Ti aiuta a rendere il CV più leggibile, completo e coerente con le candidature online.</p></div><div className="card p-5 sm:p-7">{!checked ? <Empty text="Il risultato apparirà qui dopo l’analisi." /> : <><Score score={result.score} /><div className="mt-7 grid gap-6 sm:grid-cols-2"><ResultList title="Punti forti" items={result.strengths} good /><ResultList title="Problemi da correggere" items={result.issues} /></div><div className="mt-6 rounded-2xl bg-[#f3f5f1] p-5"><h3 className="font-bold">Sezioni mancanti</h3><p className="mt-2 text-sm leading-6 text-[#5e6c69]">{result.missing.length ? result.missing.join(", ") : "Nessuna tra le sezioni principali controllate."}</p></div><div className="mt-4 rounded-2xl bg-[#f3f5f1] p-5"><h3 className="font-bold">Suggerimenti pratici</h3><p className="mt-2 text-sm leading-6 text-[#5e6c69]">Usa risultati concreti nelle esperienze, verifica le date e adatta il lessico all’annuncio solo quando descrive competenze reali.</p></div><div className="mt-4"><h3 className="font-bold">Parole ricorrenti nel CV</h3><div className="mt-3 flex flex-wrap gap-2">{result.keywords.length ? result.keywords.map((x) => <span className="rounded-lg bg-[#e8f1ec] px-3 py-1 text-sm font-bold text-[#176b4d]" key={x}>{x}</span>) : <span className="text-sm text-[#5e6c69]">Nessuna parola chiave sufficiente.</span>}</div></div><div className="mt-6 border-t border-[#e0e5e1] pt-5"><span className="text-xs font-bold uppercase tracking-wider text-[#687570]">Nome file suggerito</span><p className="mt-2 font-bold">{filename}-cv.pdf</p></div></>}</div></div>;
}

function Score({ score }: { score: number }) { return <div className="flex items-center gap-5"><div className="grid size-24 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#176b4d ${score}%, #e5ebe6 0)` }}><div className="grid size-[76px] place-items-center rounded-full bg-white text-2xl font-black">{score}</div></div><div><p className="eyebrow">Punteggio ATS</p><p className="mt-2 text-sm text-[#5e6c69]">Controllo tecnico e di completezza su 100.</p></div></div>; }
function ResultList({ title, items, good = false }: { title: string; items: string[]; good?: boolean }) { return <div><h3 className="font-bold">{title}</h3><ul className="mt-3 grid gap-2 text-sm leading-6 text-[#5e6c69]">{items.length ? items.map((x) => <li className="flex gap-2" key={x}><span className={good ? "text-[#176b4d]" : "text-[#a7433b]"}>{good ? "✓" : "•"}</span>{x}</li>) : <li>Nessun elemento da mostrare.</li>}</ul></div>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-[300px] place-items-center rounded-2xl border border-dashed border-[#cad5cd] bg-[#f7f8f4] p-6 text-center text-[#65736f]">{text}</div>; }
