"use client";

import { useState } from "react";

async function copy(text: string, setCopied: (x: boolean) => void) { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }

export function LetterGenerator() {
  const [form, setForm] = useState({ name: "", role: "", company: "", level: "prime esperienze", motivation: "", tone: "moderno", type: "risposta ad annuncio" }); const [done, setDone] = useState(false); const [copied, setCopied] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  const opening = form.tone === "formale" ? "Gentile Responsabile della selezione," : form.tone === "semplice" ? "Buongiorno," : "Gentile team di selezione,";
  const letter = `${opening}\n\nmi chiamo ${form.name || "[Nome]"} e desidero proporre la mia candidatura per il ruolo di ${form.role || "[Ruolo]"}${form.company ? ` presso ${form.company}` : ""}. Si tratta di una ${form.type}, coerente con il percorso che sto costruendo.\n\nIl mio livello professionale è ${form.level}. ${form.motivation || "Mi interessa questa opportunità perché posso mettere a disposizione competenze pertinenti e continuare a crescere in un contesto coerente con i miei obiettivi."}\n\nNel curriculum allegato ho raccolto le esperienze e le competenze più rilevanti. Sarei lieto/a di approfondire in un colloquio come potrei contribuire al ruolo e conoscere meglio le vostre esigenze.\n\nGrazie per l’attenzione.\nCordiali saluti,\n${form.name || "[Nome]"}`;
  return <GeneratorLayout inputs={<><Field label="Nome" value={form.name} onChange={(x) => update("name", x)} /><Field label="Ruolo" value={form.role} onChange={(x) => update("role", x)} /><Field label="Azienda" value={form.company} onChange={(x) => update("company", x)} /><Select label="Livello di esperienza" value={form.level} onChange={(x) => update("level", x)} options={["prime esperienze", "junior", "intermedio", "senior"]} /><Select label="Tono" value={form.tone} onChange={(x) => update("tone", x)} options={["formale", "moderno", "semplice"]} /><Select label="Tipo" value={form.type} onChange={(x) => update("type", x)} options={["risposta ad annuncio", "candidatura spontanea", "stage", "primo lavoro", "cambio carriera"]} /><label className="label sm:col-span-2">Motivazione<textarea className="input min-h-28" value={form.motivation} onChange={(e) => update("motivation", e.target.value)} placeholder="Perché ti interessa il ruolo? Quale contributo concreto puoi offrire?" /></label><button className="btn btn-primary sm:col-span-2 sm:w-fit" onClick={() => setDone(true)}>Genera la lettera</button></>} output={done ? <><pre className="whitespace-pre-wrap font-sans text-sm leading-7 text-[#354440]">{letter}</pre><button className="btn btn-secondary mt-5" onClick={() => copy(letter, setCopied)}>{copied ? "Copiata" : "Copia la lettera"}</button><p className="mt-4 text-xs leading-5 text-[#65736f]">Personalizza la bozza e verifica ogni informazione prima di inviarla.</p></> : null} />;
}

export function EmailGenerator() {
  const [form, setForm] = useState({ name: "", role: "", company: "", type: "invio CV" }); const [done, setDone] = useState(false); const [copied, setCopied] = useState("");
  const update = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  const subjectMap: Record<string,string> = { "invio CV": `Candidatura ${form.role || "[Ruolo]"} - ${form.name || "[Nome]"}`, "candidatura spontanea": `Candidatura spontanea area ${form.role || "[Ruolo]"} - ${form.name || "[Nome]"}`, "follow up candidatura": `Riscontro candidatura ${form.role || "[Ruolo]"} - ${form.name || "[Nome]"}`, "ringraziamento dopo colloquio": `Grazie per il colloquio - ${form.role || "[Ruolo]"}` };
  const intros: Record<string,string> = { "invio CV": "desidero sottoporre la mia candidatura", "candidatura spontanea": "desidero proporre la mia candidatura spontanea", "follow up candidatura": "scrivo per chiedere cortesemente un aggiornamento sulla candidatura inviata", "ringraziamento dopo colloquio": "la ringrazio per il tempo dedicato durante il colloquio" };
  const body = `Buongiorno,\n\n${intros[form.type]} per il ruolo di ${form.role || "[Ruolo]"}${form.company ? ` presso ${form.company}` : ""}. Il mio percorso e le mie competenze sono descritti nel CV allegato.\n\nResto a disposizione per un approfondimento e ringrazio per l’attenzione.\n\nCordiali saluti,\n${form.name || "[Nome]"}`;
  const doCopy = async (value: string, key: string) => { await navigator.clipboard.writeText(value); setCopied(key); window.setTimeout(() => setCopied(""), 1600); };
  return <GeneratorLayout inputs={<><Field label="Nome" value={form.name} onChange={(x) => update("name", x)} /><Field label="Ruolo" value={form.role} onChange={(x) => update("role", x)} /><Field label="Azienda" value={form.company} onChange={(x) => update("company", x)} /><Select label="Tipo di email" value={form.type} onChange={(x) => update("type", x)} options={["invio CV", "candidatura spontanea", "follow up candidatura", "ringraziamento dopo colloquio"]} /><button className="btn btn-primary sm:col-span-2 sm:w-fit" onClick={() => setDone(true)}>Genera l’email</button></>} output={done ? <><div><span className="text-xs font-bold uppercase tracking-wider text-[#65736f]">Oggetto</span><p className="mt-2 font-bold">{subjectMap[form.type]}</p><button className="mt-3 text-sm font-bold text-[#176b4d]" onClick={() => doCopy(subjectMap[form.type], "subject")}>{copied === "subject" ? "Copiato" : "Copia oggetto"}</button></div><div className="mt-6 border-t border-[#e1e6e2] pt-6"><pre className="whitespace-pre-wrap font-sans text-sm leading-7 text-[#354440]">{body}</pre><button className="btn btn-secondary mt-5" onClick={() => doCopy(body, "body")}>{copied === "body" ? "Copiata" : "Copia email"}</button></div></> : null} />;
}

function GeneratorLayout({ inputs, output }: { inputs: React.ReactNode; output: React.ReactNode }) { return <div className="grid gap-6 lg:grid-cols-2"><div className="card grid content-start gap-4 p-5 sm:grid-cols-2 sm:p-7">{inputs}</div><div className="card p-5 sm:p-7">{output ?? <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-[#cad5cd] bg-[#f7f8f4] text-center text-[#65736f]">La bozza apparirà qui.</div>}</div></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (x: string) => void }) { return <label className="label">{label}<input className="input" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (x: string) => void; options: string[] }) { return <label className="label">{label}<select className="input" value={value} onChange={(e) => onChange(e.target.value)}>{options.map((x) => <option key={x}>{x}</option>)}</select></label>; }
