"use client";

import { useMemo, useState } from "react";
import { matchTexts } from "@/lib/analysis";

export function JobMatcher() {
  const [cv, setCv] = useState(""); const [ad, setAd] = useState(""); const [done, setDone] = useState(false);
  const result = useMemo(() => matchTexts(cv, ad), [cv, ad]);
  const topMissing = result.missing.slice(0, 5);
  return <div className="grid gap-6"><div className="card grid gap-5 p-5 sm:p-7 lg:grid-cols-2"><label className="label">Testo del CV<textarea className="input min-h-64 resize-y" value={cv} onChange={(e) => { setCv(e.target.value); setDone(false); }} placeholder="Incolla il testo del CV" /></label><label className="label">Annuncio di lavoro<textarea className="input min-h-64 resize-y" value={ad} onChange={(e) => { setAd(e.target.value); setDone(false); }} placeholder="Incolla il testo completo dell’annuncio" /></label><button disabled={!cv.trim() || !ad.trim()} onClick={() => setDone(true)} className="btn btn-primary lg:col-span-2 lg:w-fit">Confronta i testi</button></div>{done && <div className="card p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="text-5xl font-black text-[#176b4d]">{result.score}%</div><div><h2 className="title-md">Corrispondenza lessicale</h2><p className="mt-2 text-sm text-[#5e6c69]">Misura quante parole rilevanti dell’annuncio compaiono nel CV, non la tua idoneità al ruolo.</p></div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><KeywordBox title="Parole trovate" words={result.found} good /><KeywordBox title="Parole da valutare" words={result.missing} /></div><div className="mt-6 grid gap-4 lg:grid-cols-3"><Suggestion title="Competenze probabilmente importanti" text={topMissing.length ? `Valuta se possiedi e puoi dimostrare: ${topMissing.join(", ")}.` : "Le principali parole dell’annuncio sono già presenti; controlla comunque che siano sostenute da esempi."} /><Suggestion title="Profilo professionale suggerito" text={`Professionista orientato al ruolo, con esperienza pertinente in ${result.found.slice(0,3).join(", ") || "attività coerenti con la posizione"}. Personalizza questa frase con anni, settore e contributo concreto.`} /><Suggestion title="Angolo per la lettera" text={`Collega la tua motivazione a ${[...result.found, ...result.missing].slice(0,3).join(", ") || "due requisiti centrali dell’annuncio"}, citando un episodio reale.`} /></div><div className="mt-4 rounded-2xl border border-[#dfe5df] p-5"><h3 className="font-bold">Come migliorare i punti esperienza</h3><p className="mt-2 text-sm leading-6 text-[#5e6c69]">Trasforma mansioni generiche in frasi con azione, contesto e risultato verificabile. Esempio: “Gestito il flusso ordini con [strumento], rispettando [criterio reale]”. Non aggiungere parole mancanti se non rappresentano competenze effettive.</p></div></div>}</div>;
}
function KeywordBox({ title, words, good = false }: { title: string; words: string[]; good?: boolean }) { return <div className="rounded-2xl bg-[#f3f5f1] p-5"><h3 className="font-bold">{title}</h3><div className="mt-3 flex flex-wrap gap-2">{words.length ? words.map((word) => <span className={`rounded-lg px-3 py-1 text-sm font-bold ${good ? "bg-[#dcece2] text-[#176b4d]" : "bg-[#f0e3e0] text-[#8b3933]"}`} key={word}>{word}</span>) : <span className="text-sm text-[#5e6c69]">Nessuna.</span>}</div></div>; }
function Suggestion({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-[#dfe5df] p-5"><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5e6c69]">{text}</p></div>; }
